### ISSUE TITLE
Question of testing after training completion

### ISSUE THREAD

**Issue by 1Shuangjiang1** [xiaofang007/ViP#5]
Hello author, I have successfully completed the model training steps. After the training is completed, how can I put the trained parameters into the model and test them with new images?

Your guidance would be greatly appreciated! Thank you again for your time and for sharing your work.

**Comment by xiaofang007** [comment]
Hi, I think you might double check the last few lines of program output (output log) because the script performs testing after training automatically.

**Comment by 1Shuangjiang1** [comment]
Thank you for your reply. I apologize for not expressing my question clearly. I saw in Fig.3 (II) of your paper that there is similarity information between pathological images and related descriptions, but running the training script cannot obtain this information. So how should I obtain similarity informat？
![屏幕截图 2024-10-12 102231](https://github.com/user-attachments/assets/aeefa61c-db28-4235-97a1-6675fe2e4198)

**Comment by xiaofang007** [comment]
Hi, sorry for the confusion. Since the visual symptom are obtained using GPT-4, they are fixed before feeding into the pipeline. Therefore, you might compare the similarity between image embedding (by processing image in a pre-trained clip image encoder) and text embedding (by processing each visual symptom in a pre-trained clip text encoder) directly. Since this part is not strongly related to the pipeline, I did not upload it.
